server:
  port:  8088
  tomcat:
    accesslog:
      enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: questerium
    password: questerapp
    url: jdbc:mysql://localhost:3306/questerium?serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  minio:
    url: http://localhost:9000/
    bucket: questerium
    access-key: questerium
    secret-key: 9b88ab4b639fc4ba54d635b9c68c27e5