server:
  port: 8088
  tomcat:
    accesslog:
      enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: questerapp
    url: jdbc:mysql://localhost:3306/questerium?serverTimezone=UTC
    username: questerium
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  minio:
    access-key: questerium
    bucket: questerium
    secret-key: 9b88ab4b639fc4ba54d635b9c68c27e5
    url: http://localhost:9000/